export const architectureManifest = {
  version: 'dg-os.architecture/v1',
  sourceRoot: 'src',
  sourceExtensions: ['.ts', '.tsx', '.astro', '.js', '.mjs'],
  zones: [
    {
      id: 'publication-receiver',
      description: 'Stateless receiver verification and exact trusted-key resolution.',
      matches: [/^src\/publication\/receiver\/(?:service|trustStore)\.ts$/],
      mayImport: ['publication-contracts', 'publication-crypto', 'publication-receiver'],
    },
    {
      id: 'publication-crypto',
      description: 'Server or local-service signing and verification for publication bundles.',
      matches: [/^src\/publication\/crypto\.ts$/],
      mayImport: ['publication-contracts', 'publication-crypto'],
    },
    {
      id: 'publication-contracts',
      description:
        'Provider-neutral publication bundle schemas, canonicalization, and pure validation.',
      matches: [/^src\/publication\/(?:canonical|contracts|index|validation|verification)\.ts$/],
      mayImport: ['publication-contracts', 'profile-contracts'],
    },
    {
      id: 'profile-contracts',
      description: 'Provider-neutral profile and module schemas plus pure validation.',
      matches: [
        /^src\/profiles\/contracts\.ts$/,
        /^src\/profiles\/validation\.ts$/,
        /^src\/profiles\/modules\/(?:contracts|applicationValidation|validation)\.ts$/,
        /^src\/profiles\/network\/(?:contracts|validation)\.ts$/,
        /^src\/profiles\/writing\/(?:contracts|validation)\.ts$/,
        /^src\/profiles\/resume\/(?:contracts|referenceValidation|validation)\.ts$/,
      ],
      mayImport: ['profile-contracts'],
    },
    {
      id: 'profile-data',
      description: 'Reviewed public profile fixtures and module content.',
      matches: [
        /^src\/profiles\/dessi\.ts$/,
        /^src\/profiles\/modules\/dessi(?:Workbench|EvidenceEvolution)?\.ts$/,
        /^src\/profiles\/network\/dessi\.ts$/,
        /^src\/profiles\/writing\/dessi\.ts$/,
        /^src\/profiles\/resume\/dessi\.ts$/,
      ],
      mayImport: ['profile-contracts', 'profile-data'],
    },
    {
      id: 'profile-runtime',
      description: 'Public profile and module registries and their public exports.',
      matches: [
        /^src\/profiles\/(?:index|runtime|cvRuntime)\.ts$/,
        /^src\/profiles\/modules\/(?:index|runtime)\.ts$/,
        /^src\/profiles\/network\/(?:index|runtime)\.ts$/,
        /^src\/profiles\/writing\/(?:index|runtime)\.ts$/,
        /^src\/profiles\/resume\/(?:index|runtime|viewModel|markdown)\.ts$/,
      ],
      mayImport: ['profile-contracts', 'profile-data', 'profile-runtime'],
    },
    {
      id: 'profile-agent',
      description: 'Explicit assembly of a profile with its approved agent evidence.',
      matches: [/^src\/profiles\/agentEvidence\.ts$/],
      mayImport: [
        'profile-contracts',
        'profile-data',
        'profile-runtime',
        'profile-agent',
        'content',
      ],
    },
    {
      id: 'api',
      description: 'Server request boundaries. Routes validate and delegate.',
      matches: [/^src\/pages\/api\//, /^src\/middleware\.ts$/],
      mayImport: [
        'api',
        'services',
        'profile-contracts',
        'profile-runtime',
        'profile-agent',
        'publication-contracts',
        'publication-receiver',
        'content',
      ],
    },
    {
      id: 'ui',
      description: 'Astro and React presentation surfaces plus non-API routes.',
      matches: [
        /^src\/components\//,
        /^src\/layouts\//,
        /^src\/pages\/(?!api\/)/,
        /^src\/assets\//,
        /^src\/styles\//,
      ],
      mayImport: [
        'ui',
        'services',
        'profile-contracts',
        'profile-data',
        'profile-runtime',
        'profile-agent',
        'content',
        'platform',
      ],
    },
    {
      id: 'services',
      description: 'Application services, deterministic reducers, gateways, and utilities.',
      matches: [/^src\/services\//, /^src\/utils\//],
      mayImport: [
        'services',
        'profile-contracts',
        'profile-data',
        'profile-runtime',
        'profile-agent',
        'content',
        'platform',
      ],
    },
    {
      id: 'content',
      description: 'Compatibility configuration, knowledge, and public content data.',
      matches: [/^src\/config\//, /^src\/knowledge\//, /^src\/data\//],
      mayImport: ['content', 'profile-contracts', 'profile-data', 'profile-runtime', 'platform'],
    },
    {
      id: 'platform',
      description: 'Shared leaf types and framework declarations.',
      matches: [/^src\/types\//, /^src\/env\.d\.ts$/],
      mayImport: ['platform'],
    },
  ],
  criticalFanOut: {
    'src/publication/receiver/service.ts': 5,
    'src/publication/receiver/trustStore.ts': 1,
    'src/publication/crypto.ts': 3,
    'src/publication/contracts.ts': 5,
    'src/publication/canonical.ts': 1,
    'src/publication/validation.ts': 6,
    'src/profiles/contracts.ts': 0,
    'src/profiles/modules/contracts.ts': 0,
    'src/profiles/validation.ts': 1,
    'src/profiles/modules/applicationValidation.ts': 1,
    'src/profiles/modules/validation.ts': 2,
    'src/profiles/network/contracts.ts': 0,
    'src/profiles/network/validation.ts': 1,
    'src/profiles/writing/contracts.ts': 0,
    'src/profiles/writing/validation.ts': 1,
    'src/profiles/resume/contracts.ts': 0,
    'src/profiles/resume/validation.ts': 2,
    'src/profiles/runtime.ts': 3,
    'src/profiles/modules/runtime.ts': 4,
    'src/profiles/network/runtime.ts': 4,
    'src/profiles/writing/runtime.ts': 4,
    'src/profiles/resume/runtime.ts': 5,
  },
};
