export const architectureManifest = {
  version: 'dg-os.architecture/v1',
  sourceRoot: 'src',
  sourceExtensions: ['.ts', '.tsx', '.astro', '.js', '.mjs'],
  zones: [
    {
      id: 'profile-contracts',
      description: 'Provider-neutral profile and module schemas plus pure validation.',
      matches: [
        /^src\/profiles\/contracts\.ts$/,
        /^src\/profiles\/validation\.ts$/,
        /^src\/profiles\/modules\/(?:contracts|applicationValidation|validation)\.ts$/,
      ],
      mayImport: ['profile-contracts'],
    },
    {
      id: 'profile-data',
      description: 'Reviewed public profile fixtures and module content.',
      matches: [
        /^src\/profiles\/dessi\.ts$/,
        /^src\/profiles\/modules\/dessi(?:Workbench|EvidenceEvolution)?\.ts$/,
      ],
      mayImport: ['profile-contracts', 'profile-data'],
    },
    {
      id: 'profile-runtime',
      description: 'Public profile and module registries and their public exports.',
      matches: [
        /^src\/profiles\/(?:index|runtime)\.ts$/,
        /^src\/profiles\/modules\/(?:index|runtime)\.ts$/,
      ],
      mayImport: ['profile-contracts', 'profile-data', 'profile-runtime'],
    },
    {
      id: 'profile-agent',
      description: 'Explicit assembly of a profile with its approved agent evidence.',
      matches: [/^src\/profiles\/agentEvidence\.ts$/],
      mayImport: [
        'profile-contracts',
        'profile-data',
        'profile-runtime',
        'profile-agent',
        'content',
      ],
    },
    {
      id: 'api',
      description: 'Server request boundaries. Routes validate and delegate.',
      matches: [/^src\/pages\/api\//, /^src\/middleware\.ts$/],
      mayImport: [
        'api',
        'services',
        'profile-contracts',
        'profile-runtime',
        'profile-agent',
        'content',
      ],
    },
    {
      id: 'ui',
      description: 'Astro and React presentation surfaces plus non-API routes.',
      matches: [
        /^src\/components\//,
        /^src\/layouts\//,
        /^src\/pages\//,
        /^src\/assets\//,
        /^src\/styles\//,
      ],
      mayImport: [
        'ui',
        'services',
        'profile-contracts',
        'profile-data',
        'profile-runtime',
        'profile-agent',
        'content',
        'platform',
      ],
    },
    {
      id: 'services',
      description: 'Application services, deterministic reducers, gateways, and utilities.',
      matches: [/^src\/services\//, /^src\/utils\//],
      mayImport: [
        'services',
        'profile-contracts',
        'profile-data',
        'profile-runtime',
        'profile-agent',
        'content',
        'platform',
      ],
    },
    {
      id: 'content',
      description: 'Compatibility configuration, knowledge, and public content data.',
      matches: [/^src\/config\//, /^src\/knowledge\//, /^src\/data\//],
      mayImport: ['content', 'profile-contracts', 'profile-data', 'profile-runtime', 'platform'],
    },
    {
      id: 'platform',
      description: 'Shared leaf types and framework declarations.',
      matches: [/^src\/types\//, /^src\/env\.d\.ts$/],
      mayImport: ['platform'],
    },
  ],
  criticalFanOut: {
    'src/profiles/contracts.ts': 0,
    'src/profiles/modules/contracts.ts': 0,
    'src/profiles/validation.ts': 1,
    'src/profiles/modules/applicationValidation.ts': 1,
    'src/profiles/modules/validation.ts': 2,
    'src/profiles/runtime.ts': 3,
    'src/profiles/modules/runtime.ts': 4,
  },
};
