export const skills: readonly string[] = [
  'Python',
  'FastAPI',
  'Pytest',
  'Pydantic',
  'SQL',
  'PostgreSQL',
  'TypeScript',
  'React',
  'Next.js',
  'Astro',
  'Node.js',
  'LLM evaluation',
  'Tool-using agents',
  'Prompt and context design',
  'Embeddings',
  'Clustering',
  'AWS',
  'Terraform',
  'Docker',
  'CI/CD',
] as const;
