import { dessiProfileProjection } from '../dessi';
import {
  PUBLIC_NETWORK_SCHEMA_VERSION,
  type NetworkNode,
  type NetworkPath,
  type NetworkRelationship,
} from './contracts';
import { definePublicNetworkModule } from './validation';

const networkNodes: readonly NetworkNode[] = [
  {
    id: 'foundation-systems-knowledge',
    kind: 'Foundation',
    title: 'Systems & Knowledge',
    subtitle: 'Philosophy of science',
    period: '2003–2007',
    evidence: 'Background',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance: 'BA Philosophy, Sofia University.',
    boundary:
      'Academic background explains an enduring interest in knowledge and systems; it is not evidence of engineering capability by itself.',
    tags: ['philosophy of science', 'knowledge', 'systems', 'reasoning'],
    bullets: [
      'Studied how knowledge claims are formed, tested, and revised.',
      'Provides intellectual context for later interest in inspectable systems.',
    ],
    map: { column: 0, row: 0 },
  },
  {
    id: 'foundation-human-systems',
    kind: 'Foundation',
    title: 'Human Systems',
    subtitle: 'Applied human rights',
    period: '2009–2011',
    evidence: 'Background',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance: 'MA Applied Human Rights, University of York.',
    boundary:
      'This background informs questions about agency and accountability without establishing that every later design decision follows directly from it.',
    tags: ['human rights', 'agency', 'ethics', 'accountability'],
    bullets: [
      'Studied institutions, power, rights, and practical accountability.',
      'Offers context for the emphasis on human control in agent systems.',
    ],
    map: { column: 0, row: 1 },
  },
  {
    id: 'career-data-operations',
    kind: 'Career',
    title: 'Data Operations',
    subtitle: 'Mission-led and marketing organisations',
    period: '2012–2019',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'private-employer',
    provenance:
      'Roles spanning nonprofit operations, CRM data, SQL, segmentation, and data quality.',
    boundary:
      'This node compresses several early roles into one career era; detailed chronology remains in the Resume.',
    tags: ['sql', 'crm', 'data quality', 'segmentation', 'operations'],
    bullets: [
      'Built foundations in database stewardship, campaign data, and operational delivery.',
      'Moved from maintaining records toward designing repeatable data workflows.',
    ],
    map: { column: 0, row: 2.4 },
  },
  {
    id: 'career-analytics-platforms',
    kind: 'Career',
    title: 'Analytics Platforms',
    subtitle: 'BI, experimentation, and cloud data',
    period: '2019–2023',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'private-employer',
    provenance: 'Analytics and BI roles across Toaster, Founders Forum, Jellyfish, and Publicis.',
    boundary:
      'Employer systems are summarized at capability level because implementation artifacts are not publicly available.',
    tags: ['business intelligence', 'r shiny', 'aws', 'etl', 'data lakes'],
    bullets: [
      'Shifted from reporting delivery to reusable analytics products and cloud data foundations.',
      'Developed the operational habits later used in AI platform work.',
    ],
    map: { column: 0, row: 3.6 },
  },
  {
    id: 'career-ai-systems',
    kind: 'Career',
    title: 'AI Systems & Platforms',
    subtitle: 'Applied AI engineering',
    period: '2023–Present',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'private-employer',
    provenance: 'Professional work in Publicis and Performics innovation environments.',
    boundary:
      'Paid-work claims are intentionally high level. Public projects elsewhere in the map provide supporting, but not equivalent, evidence.',
    tags: [
      'agent systems',
      'multi-tenant platforms',
      'identity',
      'programmatic tools',
      'infrastructure',
    ],
    bullets: [
      'Builds agent systems, typed tool contracts, policy boundaries, multi-tenant platforms, and infrastructure controls.',
      'Develops a Programmatic plugin spanning agent skills, CLI and backend tools, tenant-bound execution, approval, and recovery.',
    ],
    map: { column: 0, row: 4.8 },
  },
  {
    id: 'practice-identity-policy',
    kind: 'Practice',
    title: 'Identity & Policy',
    subtitle: 'Who may act, where, and with whose approval',
    evidence: 'Practice',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance:
      'Recurring pattern across auth, tenant isolation, agent permissions, and approval gates.',
    boundary: 'A cross-project design practice, not a standalone shipped product.',
    tags: ['identity', 'policy', 'approval gates', 'tenant isolation', 'audit'],
    bullets: [
      'Separates user, agent, tenant, capability, and approval boundaries.',
      'Makes consequential automation conditional and reviewable.',
    ],
    map: { column: 1, row: 0.5 },
  },
  {
    id: 'practice-learning-loops',
    kind: 'Practice',
    title: 'Learning Loops',
    subtitle: 'Observe, update, and retain uncertainty',
    evidence: 'Practice',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance: 'Implemented most explicitly in the Agentic Commerce prototype.',
    boundary:
      'Prototype learning loops demonstrate architecture and policy behavior, not commercial uplift.',
    tags: ['belief updates', 'feedback', 'memory', 'uncertainty', 'validation'],
    bullets: [
      'Keeps simulation, observation, belief update, and memory distinct.',
      'Uses confidence gates before learned state is reused.',
    ],
    map: { column: 1, row: 1.8 },
  },
  {
    id: 'practice-evaluation-evidence',
    kind: 'Practice',
    title: 'Evaluation & Evidence',
    subtitle: 'Claims remain tied to observable artifacts',
    evidence: 'Practice',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance:
      'Visible in tests, validation receipts, deterministic projections, and portfolio boundaries.',
    boundary:
      'Test volume and structured evidence improve confidence but do not establish real-world impact alone.',
    tags: ['evaluation', 'provenance', 'testing', 'receipts', 'limitations'],
    bullets: [
      'Separates what was built, simulated, observed, and inferred.',
      'Treats limitations as part of the evidence rather than as footnotes.',
    ],
    map: { column: 1, row: 3.1 },
  },
  {
    id: 'practice-infrastructure-reliability',
    kind: 'Practice',
    title: 'Infrastructure Reliability',
    subtitle: 'Contracts, reproducibility, and controlled change',
    evidence: 'Practice',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance: 'Professional infrastructure work and public system-design patterns.',
    boundary:
      'Private infrastructure details are not disclosed; the map records the operating pattern only.',
    tags: ['infrastructure as code', 'contracts', 'drift', 'ephemeral environments'],
    bullets: [
      'Uses reproducible environments and contract checks to reduce operational ambiguity.',
      'Treats cleanup, drift, and recovery as product responsibilities.',
    ],
    map: { column: 1, row: 4.4 },
  },
  {
    id: 'system-ai-news-hub',
    kind: 'System',
    title: 'Performics Labs AI News Hub',
    subtitle: 'Applied AI research for marketing practice',
    period: '2024–Present',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance: 'Public live site and MIT-licensed repository.',
    boundary:
      'The platform is publicly verifiable. Its internal community purpose and approximate membership are owner-reported, and public bylines may represent collaborative work.',
    tags: ['applied ai research', 'marketing', 'publishing platform', 'community', 'open source'],
    bullets: [
      'Gives marketing practitioners, strategists, and engineers a shared place to understand what fast-moving AI changes mean in practice.',
      'Connects news, analysis, build sessions, and prototypes so research can lead to implementation.',
    ],
    map: { column: 2, row: 0 },
    links: {
      url: 'https://ai-news-hub.performics-labs.com/',
      repo: 'https://github.com/ai-knowledge-hub/performics_labs_ai_news',
    },
  },
  {
    id: 'system-ai-skills',
    kind: 'System',
    title: 'AI Skills Platform',
    subtitle: 'Reusable implementations of applied AI research',
    period: '2024–Present',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance: 'Public AI Knowledge Hub site, repository, and generated registries.',
    boundary:
      'The public catalog demonstrates reusable skill design; adoption and production impact require separate evidence.',
    tags: ['skills', 'agents', 'plugins', 'tools', 'agent operations', 'open source'],
    bullets: [
      'Turns practical research into packages that teams can inspect, install, test, and adapt.',
      'Publishes readiness, usability, permissions, and approval boundaries across skills, agents, plugins, and tools.',
    ],
    map: { column: 2, row: 1 },
    links: {
      url: 'https://skills.ai-knowledge-hub.org/',
      repo: 'https://github.com/ai-knowledge-hub/ai-skills-guide',
    },
  },
  {
    id: 'system-gateplane',
    kind: 'System',
    title: 'Gateplane',
    subtitle: 'Identity, authority, and agent-execution control',
    period: '2025–Present',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'private-employer',
    provenance: 'Private project developed from enterprise authentication requirements.',
    boundary:
      'The repository is private. Claims are limited to the architecture Dessi can describe without exposing employer or client material.',
    tags: ['oidc', 'entra', 'rbac', 'multi-tenant auth', 'agent execution', 'capability gating'],
    bullets: [
      'Models tenant, organisation, workspace, role, capability, grant, and approval boundaries.',
      'Places deterministic execution, evidence, and publication gates around model-proposed work.',
    ],
    map: { column: 2, row: 2 },
  },
  {
    id: 'system-intent-recognition',
    kind: 'System',
    title: 'Intent Recognition',
    subtitle: 'Inspectable intent-inference prototype',
    period: '2024–Present',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance:
      'Public repository and prototype derived from an applied marketing-intelligence question.',
    boundary:
      'The prototype demonstrates architecture and inference patterns; it is not evidence of production prediction accuracy.',
    tags: ['intent', 'embeddings', 'clustering', 'multi-agent', 'marketing intelligence'],
    bullets: [
      'Combines context capture, intent taxonomy, embeddings, clustering, and activation.',
      'Makes confidence and intermediate reasoning inspectable.',
    ],
    map: { column: 2, row: 3 },
    links: {
      repo: 'https://github.com/ai-knowledge-hub/deep-dive-analysis-intent-recognition-agent',
      url: 'https://huggingface.co/spaces/Dessi/gradio-mcp-hack',
    },
  },
  {
    id: 'system-agentic-commerce',
    kind: 'System',
    title: 'Agentic Commerce',
    subtitle: 'Evidence-learning engine and governed agent control plane',
    period: '2024–Present',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance: 'Public repository with implementation, tests, and technical writing.',
    boundary:
      'Observed and simulated validation remain distinct; the prototype does not claim commercial performance.',
    tags: ['agentic commerce', 'learning loops', 'multi-tenant', 'validation'],
    bullets: [
      'Updates product beliefs through simulated and observed validation without silently retraining the model.',
      'Combines confidence-gated memory and belief revision with scoped tools, policy, receipts, and recovery.',
    ],
    map: { column: 2, row: 4 },
    links: {
      repo: 'https://github.com/ai-knowledge-hub/deep-dive-analysis-agentic-commerce-augmentation',
      article:
        'https://ai-news-hub.performics-labs.com/analysis/building-to-learn-agentic-marketing-optimization',
    },
  },
  {
    id: 'system-enterprise-automation',
    kind: 'System',
    title: 'Enterprise Automation',
    subtitle: 'Multi-tenant marketing and ecommerce systems',
    period: '2023–Present',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'private-employer',
    provenance: 'Paid platform work across marketing automation and ecommerce optimization.',
    boundary:
      'Client and employer implementation details remain private; only architectural scope and publicly verifiable recognition are included.',
    tags: [
      'multi-tenant',
      'aws',
      'databricks',
      'programmatic plugin',
      'campaign optimization',
      'ecommerce',
    ],
    bullets: [
      'Connects tenant-aware data, analytics, optimization, and execution workflows.',
      'Includes a Programmatic plugin with agent-selected skills, a typed CLI, backend tool policy, human approval, and deterministic write gates.',
      'Includes backend and AWS delivery for an award-recognized ecommerce platform.',
    ],
    map: { column: 2, row: 5 },
    links: {
      article:
        'https://www.performancemarketingworldawards.com/finalists/unifying-retail-data-with-publicis-warehouse-7y3bxeifqg035ne',
    },
  },
  {
    id: 'system-onesuite-infrastructure',
    kind: 'System',
    title: 'OneSuite Infrastructure',
    subtitle: 'Ephemeral environments and lifecycle control',
    period: '2025–Present',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'private-employer',
    provenance: 'Paid infrastructure work in the OneSuite platform environment.',
    boundary:
      'Operational details and source remain private; the map records the reproducibility and governance pattern.',
    tags: ['terraform', 'aws', 'ephemeral environments', 'drift', 'decommissioning'],
    bullets: [
      'Replaces legacy infrastructure with reproducible scratch environments.',
      'Adds contract checks, drift awareness, and controlled lifecycle operations.',
    ],
    map: { column: 2, row: 6 },
  },
  {
    id: 'system-human-systems-platform',
    kind: 'System',
    title: 'Human Systems Platform',
    subtitle: 'Owner-controlled evidence and learning network for human-AI work',
    period: '2026–Present',
    evidence: 'Professional context',
    evidenceConfidence: 'self-reported',
    evidenceVisibility: 'public',
    provenance:
      'Private working repository reviewed alongside the public Learning Foundry and DG-OS components.',
    boundary:
      'The product is in private active development. Working contracts and prototypes do not yet establish an integrated product, customer demand, beneficial outcomes, or product-market fit.',
    tags: [
      'founder product',
      'human-ai work',
      'learning',
      'evidence',
      'owner control',
      'talent discovery',
    ],
    bullets: [
      'Turns selected experience into private learning, owner-approved evidence, bounded opportunity hypotheses, and later correction.',
      'Connects Dessi Space, Learning Foundry, DG-OS, and a planned Organization Foundry without merging their private records or authority.',
    ],
    map: { column: 2, row: 8 },
  },
  {
    id: 'system-dg-os',
    kind: 'System',
    title: 'DG-OS',
    subtitle: 'Owner-approved public evidence and professional discovery',
    period: '2025–Present',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance: 'The portfolio application currently being inspected.',
    boundary:
      'The current release is the reviewed public projection plane; automated ingestion and end-to-end receiver-observed publication remain incomplete.',
    tags: ['portfolio', 'knowledge interface', 'agents', 'evidence'],
    bullets: [
      'Gives the owner a richer professional presence than a static CV and gives visitors evidence they can inspect rather than unsupported claims.',
      'Acts as the public expression and discovery product within Human Systems Platform while remaining functional on its own.',
    ],
    map: { column: 2, row: 9 },
    links: {
      repo: 'https://github.com/DG-creative-lab/dg-labs-os',
      url: 'https://dg-os.com/',
    },
  },
  {
    id: 'evidence-technical-writing',
    kind: 'Evidence',
    title: 'Technical Writing',
    subtitle: 'Selected Performics Labs analysis',
    period: '2024–Present',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance: 'Published under the Performics Labs byline.',
    boundary:
      'Professional technical writing demonstrates synthesis and communication, not independent academic research or sole authorship.',
    tags: ['technical writing', 'architecture', 'analysis', 'communication'],
    bullets: [
      'Documents architecture questions connected to systems built or investigated.',
      'Selected pieces state their related system and limitations.',
    ],
    map: { column: 3, row: 1.2 },
    links: {
      url: 'https://ai-news-hub.performics-labs.com/analysis',
    },
  },
  {
    id: 'system-learning-foundry',
    kind: 'System',
    title: 'Learning Foundry',
    subtitle: 'Human learning and separately governed agent development',
    period: '2026',
    evidence: 'Public artifact',
    evidenceConfidence: 'verified',
    evidenceVisibility: 'public',
    provenance: 'OpenAI Build Week submission preserved at the submitted commit.',
    boundary:
      'The linked state is a hackathon prototype. It demonstrates a functional learning product and evidence model, while longitudinal use and full platform integration remain under development.',
    tags: ['constructive learning', 'evidence ledger', 'consent', 'agent memory'],
    bullets: [
      'Helps a person explain, practise, apply, and revise knowledge while keeping original sources and corrections visible.',
      'Develops evaluated agent capabilities separately from human understanding and contributes only curated evidence to the wider platform.',
    ],
    map: { column: 2, row: 7 },
    links: {
      repo: 'https://github.com/DG-creative-lab/codex-hack-learning-foundry/tree/0547da02518f432fdd85e79d317e1fedaa51c4c1',
    },
  },
] as const;

const networkRelationships: readonly NetworkRelationship[] = [
  {
    id: 'foundation-knowledge-to-evaluation',
    from: 'foundation-systems-knowledge',
    to: 'practice-evaluation-evidence',
    relation: 'informed',
    evidence: 'Both focus on how claims are formed, tested, and revised.',
    confidence: 'interpretive',
    evidenceVisibility: 'public',
  },
  {
    id: 'foundation-human-to-policy',
    from: 'foundation-human-systems',
    to: 'practice-identity-policy',
    relation: 'informed',
    evidence: 'Human control and accountability recur in later agent-policy work.',
    confidence: 'interpretive',
    evidenceVisibility: 'public',
  },
  {
    id: 'career-data-to-analytics',
    from: 'career-data-operations',
    to: 'career-analytics-platforms',
    relation: 'led to',
    evidence: 'Career chronology moved from operational data work into analytics products.',
    confidence: 'direct',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'career-analytics-to-ai',
    from: 'career-analytics-platforms',
    to: 'career-ai-systems',
    relation: 'led to',
    evidence:
      'Cloud data and product analytics became the foundation for applied AI platform work.',
    confidence: 'direct',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'career-ai-to-news',
    from: 'career-ai-systems',
    to: 'system-ai-news-hub',
    relation: 'built during',
    evidence:
      'The platform was developed in the Performics innovation context as a shared applied AI research space.',
    confidence: 'supported',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'career-ai-to-enterprise',
    from: 'career-ai-systems',
    to: 'system-enterprise-automation',
    relation: 'built during',
    evidence: 'Enterprise automation is part of Dessi’s paid AI-platform scope.',
    confidence: 'supported',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'career-ai-to-gateplane',
    from: 'career-ai-systems',
    to: 'system-gateplane',
    relation: 'built during',
    evidence: 'Gateplane grew from enterprise multi-tenant identity requirements.',
    confidence: 'supported',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'career-ai-to-intent',
    from: 'career-ai-systems',
    to: 'system-intent-recognition',
    relation: 'built during',
    evidence:
      'The public prototype represents applied intent work developed in an innovation context.',
    confidence: 'supported',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'career-ai-to-commerce',
    from: 'career-ai-systems',
    to: 'system-agentic-commerce',
    relation: 'built during',
    evidence: 'The public prototype expands an applied agentic-commerce question.',
    confidence: 'supported',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'career-ai-to-infrastructure',
    from: 'career-ai-systems',
    to: 'system-onesuite-infrastructure',
    relation: 'built during',
    evidence: 'The infrastructure work belongs to Dessi’s current professional platform scope.',
    confidence: 'supported',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'identity-to-gateplane',
    from: 'practice-identity-policy',
    to: 'system-gateplane',
    relation: 'applied in',
    evidence: 'Gateplane explicitly models tenant, role, and capability boundaries.',
    confidence: 'direct',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'identity-to-enterprise',
    from: 'practice-identity-policy',
    to: 'system-enterprise-automation',
    relation: 'applied in',
    evidence:
      'Enterprise platforms require tenant isolation, authentication, and controlled execution.',
    confidence: 'supported',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'identity-to-learning-foundry',
    from: 'practice-identity-policy',
    to: 'system-learning-foundry',
    relation: 'applied in',
    evidence: 'Learning Foundry separates preparation from consent-gated activation.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'learning-to-commerce',
    from: 'practice-learning-loops',
    to: 'system-agentic-commerce',
    relation: 'applied in',
    evidence: 'Belief updates, validation, and memory reuse are implemented in the prototype.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'evaluation-to-commerce',
    from: 'practice-evaluation-evidence',
    to: 'system-agentic-commerce',
    relation: 'applied in',
    evidence:
      'Tests and receipts distinguish simulation, observation, replay, recovery, and policy.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'evaluation-to-learning-foundry',
    from: 'practice-evaluation-evidence',
    to: 'system-learning-foundry',
    relation: 'applied in',
    evidence: 'The prototype uses append-only evidence and deterministic projections.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'infrastructure-to-onesuite',
    from: 'practice-infrastructure-reliability',
    to: 'system-onesuite-infrastructure',
    relation: 'applied in',
    evidence: 'Ephemeral stacks, drift checks, and lifecycle control define the system.',
    confidence: 'direct',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'infrastructure-to-enterprise',
    from: 'practice-infrastructure-reliability',
    to: 'system-enterprise-automation',
    relation: 'supports',
    evidence: 'AWS delivery and data workflows depend on reproducible operational boundaries.',
    confidence: 'supported',
    evidenceVisibility: 'private-employer',
  },
  {
    id: 'news-to-skills',
    from: 'system-ai-news-hub',
    to: 'system-ai-skills',
    relation: 'informed',
    evidence:
      'AI Skills Platform was developed as the practical companion to several AI News Hub articles.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'news-to-writing',
    from: 'system-ai-news-hub',
    to: 'evidence-technical-writing',
    relation: 'supports',
    evidence:
      'The platform hosts the selected technical analysis represented in the evidence layer.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'skills-to-intent',
    from: 'system-ai-skills',
    to: 'system-intent-recognition',
    relation: 'shares pattern with',
    evidence: 'Both expose bounded capabilities to agent runtimes through explicit interfaces.',
    confidence: 'supported',
    evidenceVisibility: 'public',
  },
  {
    id: 'skills-to-dgos',
    from: 'system-ai-skills',
    to: 'system-dg-os',
    relation: 'supports',
    evidence:
      'DG-OS is intended to invoke reusable Codex capabilities as its automation layer evolves.',
    confidence: 'interpretive',
    evidenceVisibility: 'public',
  },
  {
    id: 'commerce-to-writing',
    from: 'system-agentic-commerce',
    to: 'evidence-technical-writing',
    relation: 'documented by',
    evidence:
      'Selected articles explain the prototype, readiness stack, and learning-loop boundaries.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
  {
    id: 'identity-to-writing',
    from: 'practice-identity-policy',
    to: 'evidence-technical-writing',
    relation: 'documented by',
    evidence:
      'The secure-marketing-agents reference architecture documents identity and policy boundaries.',
    confidence: 'supported',
    evidenceVisibility: 'public',
  },
  {
    id: 'evaluation-to-writing',
    from: 'practice-evaluation-evidence',
    to: 'evidence-technical-writing',
    relation: 'documented by',
    evidence:
      'Selected implementation guides explain deterministic and evidence-oriented agent patterns.',
    confidence: 'supported',
    evidenceVisibility: 'public',
  },
  {
    id: 'career-ai-to-human-systems-platform',
    from: 'career-ai-systems',
    to: 'system-human-systems-platform',
    relation: 'built during',
    evidence:
      "The founder product extends Dessi's current work on human-AI systems, evidence, authority, and capability development.",
    confidence: 'direct',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'learning-foundry-to-platform',
    from: 'system-learning-foundry',
    to: 'system-human-systems-platform',
    relation: 'supports',
    evidence:
      'Learning Foundry provides the human and agent development product and contributes curated learning evidence without sharing its private ledger.',
    confidence: 'supported',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'platform-to-dgos',
    from: 'system-human-systems-platform',
    to: 'system-dg-os',
    relation: 'supports',
    evidence:
      'The shared platform supplies the review, evidence, and publication boundary through which owner-approved material can reach DG-OS.',
    confidence: 'supported',
    evidenceVisibility: 'mixed',
  },
  {
    id: 'writing-to-dgos',
    from: 'evidence-technical-writing',
    to: 'system-dg-os',
    relation: 'presented by',
    evidence:
      'DG-OS curates the strongest technical pieces and states their provenance and limitations.',
    confidence: 'direct',
    evidenceVisibility: 'public',
  },
] as const;

const networkPaths: readonly NetworkPath[] = [
  {
    id: 'experience-to-opportunity',
    question: 'How do Learning Foundry, Human Systems Platform, and DG-OS form one product?',
    answer:
      'Learning Foundry turns approved sources and practical work into human learning and separately governed agent capabilities. Human Systems Platform preserves evidence, context, ownership, and review across the product boundaries. DG-OS publishes only the approved public representation, where it can lead to an opportunity, collaboration, research question, or investor conversation. Later outcomes are intended to correct the next learning cycle.',
    nodeIds: [
      'career-ai-systems',
      'system-learning-foundry',
      'system-human-systems-platform',
      'system-dg-os',
    ],
    relationshipIds: [
      'career-ai-to-human-systems-platform',
      'learning-foundry-to-platform',
      'platform-to-dgos',
    ],
  },
  {
    id: 'research-to-implementation',
    question: 'How does Dessi turn research into practical AI tools?',
    answer:
      'The AI News Hub gives a community a place to understand applied AI questions. AI Skills Platform turns selected ideas into reusable packages that people can inspect, install, test, and adapt.',
    nodeIds: [
      'career-ai-systems',
      'system-ai-news-hub',
      'evidence-technical-writing',
      'system-ai-skills',
    ],
    relationshipIds: ['career-ai-to-news', 'news-to-writing', 'news-to-skills'],
  },
  {
    id: 'data-to-agents',
    question: 'How did Dessi move from data work to agent systems?',
    answer:
      'Operational data work became analytics platforms, then multi-tenant AI systems where evaluation and policy are first-class concerns.',
    nodeIds: [
      'career-data-operations',
      'career-analytics-platforms',
      'career-ai-systems',
      'system-enterprise-automation',
      'system-agentic-commerce',
    ],
    relationshipIds: [
      'career-data-to-analytics',
      'career-analytics-to-ai',
      'career-ai-to-enterprise',
      'career-ai-to-commerce',
    ],
  },
  {
    id: 'commerce-credibility',
    question: 'What makes the agentic-commerce work credible?',
    answer:
      'The public prototype combines a learning-loop architecture with explicit validation, policy boundaries, tests, and writing that states what remains unproven.',
    nodeIds: [
      'career-ai-systems',
      'practice-learning-loops',
      'practice-evaluation-evidence',
      'practice-identity-policy',
      'system-agentic-commerce',
      'evidence-technical-writing',
    ],
    relationshipIds: [
      'career-ai-to-commerce',
      'learning-to-commerce',
      'evaluation-to-commerce',
      'commerce-to-writing',
      'identity-to-writing',
    ],
  },
  {
    id: 'private-to-public',
    question: 'How does private work connect to public evidence?',
    answer:
      'Paid systems establish the professional context. Public prototypes, technical writing, and DG-OS expose related design patterns without pretending to reproduce employer systems.',
    nodeIds: [
      'career-ai-systems',
      'system-enterprise-automation',
      'system-gateplane',
      'system-onesuite-infrastructure',
      'system-agentic-commerce',
      'evidence-technical-writing',
      'system-dg-os',
    ],
    relationshipIds: [
      'career-ai-to-enterprise',
      'career-ai-to-gateplane',
      'career-ai-to-infrastructure',
      'career-ai-to-commerce',
      'commerce-to-writing',
      'writing-to-dgos',
    ],
  },
] as const;

export const dessiNetworkModule = definePublicNetworkModule({
  schemaVersion: PUBLIC_NETWORK_SCHEMA_VERSION,
  profileId: dessiProfileProjection.profileId,
  handle: dessiProfileProjection.handle,
  projectionVersion: dessiProfileProjection.projectionVersion,
  networkVersion: 4,
  status: 'published',
  title: 'System Map',
  description:
    'Reviewed relationships between career experience, systems-engineering practices, active platforms, and public evidence.',
  nodes: networkNodes,
  relationships: networkRelationships,
  paths: networkPaths,
  publication: {
    approvedBy: 'owner',
    reviewedAt: '2026-08-23T00:00:00Z',
    publishedAt: '2026-08-23T00:00:00Z',
    privateSourcesExcluded: true,
    sourcePolicy:
      'Only owner-reviewed relationships, bounded claims, and public descriptions may enter this module. Raw private evidence remains excluded.',
  },
});
